title: Weeknotes! for the UKCEH Research Software Engineering in Environmental Data Science group
email: jowals@ceh.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  "Weeknotes"-style occasional updates from the Research Software Engineering group in Environmental Data Science at the UK Centre for Ecology and Hydrology"
domain: ukceh-rse.github.io
baseurl: "/weeknotes/" # the subpath of your site, e.g. /blog
url: "https://ukceh-rse.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  metazool

# Build settings
remote_theme: andreondra/jekyll-theme-simplex
plugins:
  - jekyll-feed
